apiVersion: apps/v1
kind: Deployment
metadata: 
  name: second-command-kstream-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: second-command-kstream
  template: 
    metadata: 
      labels: 
        app: second-command-kstream
    spec: 
      containers: 
        - 
          # args: 
            
          command: 
            - java
            - '-Dpair=BTCUSDT'
            - '-cp'
            - 'kafkaStreams.jar'
            - '-Dthread={ "class": "MarketDataStreamWindowedAgg", "params": {"bootstrapServers": "b-1.bayviewmsk.jdabnv.c2.kafka.ap-northeast-1.amazonaws.com:9092,b-2.bayviewmsk.jdabnv.c2.kafka.ap-northeast-1.amazonaws.com:9092", "pair": "BTCUSDT" } }'
            - 'com.tradingbot.kafka.RunThread'
          image: "126880002495.dkr.ecr.ap-northeast-1.amazonaws.com/test-ecr:v1"
          name: kstream
          resources:
            requests:
              memory: "4096Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "1000m"
